<?php
/**
 * Plugin Name: SimSpace
 * Description: Room + simulator planner (React app) embedded via shortcode.
 * Version: 0.1.0
 * Author: SimSpace
 */

if (!defined('ABSPATH')) exit;

define('SIMSPACE_PLUGIN_DIR', plugin_dir_path(__FILE__));
define('SIMSPACE_PLUGIN_URL', plugins_url('/', __FILE__));

/**
 * Locate the Vite entry in manifest.json robustly.
 */
function simspace_manifest_entry($manifest) {
  if (!is_array($manifest)) return null;
  // Prefer any entry with isEntry=true
  foreach ($manifest as $key => $val) {
    if (is_array($val) && !empty($val['isEntry'])) {
      return $val;
    }
  }
  // Fallback to common keys
  if (isset($manifest['index.html'])) return $manifest['index.html'];
  if (isset($manifest['src/main.tsx'])) return $manifest['src/main.tsx'];
  if (isset($manifest['src/main.ts'])) return $manifest['src/main.ts'];
  // Last resort: first element
  foreach ($manifest as $val) {
    if (is_array($val)) return $val;
  }
  return null;
}

/**
 * Enqueue built assets (Vite manifest-based).
 */
function simspace_enqueue_assets() {
  $assets_dir = SIMSPACE_PLUGIN_DIR . 'assets/';
  $assets_url = SIMSPACE_PLUGIN_URL . 'assets/';
  $manifest_path = $assets_dir . 'manifest.json';
  if (!file_exists($manifest_path)) return;

  $manifest = json_decode(file_get_contents($manifest_path), true);
  $entry = simspace_manifest_entry($manifest);
  if (!$entry) return;

  // Optional: enqueue Google Fonts used by the app
  wp_enqueue_style(
    'simspace-fonts',
    'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Roboto+Condensed:wght@300;700;800;900&display=swap',
    [],
    null
  );

  // CSS files emitted by Vite
  if (!empty($entry['css']) && is_array($entry['css'])) {
    foreach ($entry['css'] as $css) {
      $handle = 'simspace-' . md5($css);
      wp_enqueue_style($handle, $assets_url . $css, ['simspace-fonts'], null);
    }
  }

  // JS entry
  if (!empty($entry['file'])) {
    wp_enqueue_script('simspace-app', $assets_url . $entry['file'], [], null, true);
    // Example of passing data to the app if needed later
    wp_localize_script('simspace-app', 'SIMSPACE_BOOT', [
      'restBase' => esc_url_raw(rest_url('simspace/v1/')),
      'nonce'    => wp_create_nonce('wp_rest'),
    ]);
  }
}

/**
 * Shortcode renderer.
 * Usage: [simspace]
 */
function simspace_shortcode($atts = []) {
  $atts = shortcode_atts([
    'debug' => '0',
  ], $atts, 'simspace');

  $debug = $atts['debug'] === '1' || strtolower($atts['debug']) === 'true';

  // Minimal visible confirmation that the shortcode rendered
  $debugHtml = $debug ? '<div class="simspace-debug-banner" style="margin:12px 0;padding:10px 12px;border:1px solid #ddd;border-radius:6px;background:#f7f7f7;color:#222;font:14px/1.4 -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;">SimSpace shortcode active — assets will load if the build is present in the plugin’s assets folder.</div>' : '';

  // The app expects a div#root (per index.html)
  return '<div class="simspace-container">'.$debugHtml.'<div id="root"></div></div>';
}
add_shortcode('simspace', 'simspace_shortcode');

/**
 * Conditionally enqueue assets on pages that use the shortcode.
 */
function simspace_maybe_enqueue() {
  if (!is_singular()) return;
  global $post;
  if (!$post) return;
  if (has_shortcode($post->post_content, 'simspace')) {
    simspace_enqueue_assets();
  }
}
add_action('wp_enqueue_scripts', 'simspace_maybe_enqueue');

/**
 * Tiny settings/help page to show the shortcode and basic notes.
 */
function simspace_admin_menu() {
  add_options_page(
    'SimSpace',
    'SimSpace',
    'manage_options',
    'simspace',
    'simspace_settings_page'
  );
}
add_action('admin_menu', 'simspace_admin_menu');

function simspace_settings_page() {
  if (!current_user_can('manage_options')) return;
  ?>
  <div class="wrap">
    <h1>SimSpace</h1>
    <p>Add the app to any page or post using this shortcode:</p>
    <p><code>[simspace]</code></p>
    <p>You can upload a new build by replacing files in the plugin's <code>assets/</code> folder. The build must include a <code>manifest.json</code> generated by Vite.</p>
  </div>
  <?php
}


